### PR TITLE
Get rid of failing ciMetrics

### PR DESCRIPTION
**Pull request by thrix**
Influxdb is down, was not able to ressurect it.

We do not use these stats anyway ...

Signed-off-by: Miroslav Vadkerti <mvadkert@redhat.com>

### CODE REVIEW

**Comment by joejstuart** [comment]
This should be the line to remove. https://github.com/CentOS-PaaS-SIG/upstream-fedora-pipeline/blob/master/vars/packagepipelineUtils.groovy#L70

**Comment by thrix** [comment]
@joejstuart thanks, testing ...

**Comment by thrix** [comment]
@joejstuart not much luck ... maybe I broke something else ... just tried to comment out related things ...

**Comment by joejstuart** [comment]
@thrix Can you point me to the console log? I can take a look.

**Comment by thrix** [comment]
@joejstuart sure thing, it is the staging job of this PR: https://jenkins-continuous-infra.apps.ci.centos.org/job/fedora-stage-pipeline-trigger/162/

**Comment by thrix** [comment]
@bgoncalv fyi btw

**Comment by joejstuart** [comment]
Looks like there's an undefined variable "artifact". Not sure how the comments would have created this error though.

**Comment by bgoncalv** [comment]
The problem seems to be because timedPipelineStep got removed, but it is still being called on Jenkinsfile. This causes an exception, this exception is caught by the pipeline and it tries to send an `error` topic, but the message can't be sent because artifact variable was not defined yet.

I think we can just replace in Jenkinsfile timedPipelineStep by handlePipelineStep

**Comment by bgoncalv** [comment]
all green now. Let me know if the change is fine than I can squash the commits :)

**Comment by bgoncalv** [comment]
[citest]

**Comment by bgoncalv** [comment]
[test]

**Comment by bgoncalv** [comment]
[test]

**Comment by bgoncalv** [comment]
[merge]

**Pull request merged**
