### PR TITLE
Update s2i for new scriptApprovals

### PR DESCRIPTION
**Pull request by johnbieren**
script approvals for closure messages

Signed-off-by: Johnny Bieren <jbieren@redhat.com>

### CODE REVIEW

**Comment by johnbieren** [comment]
I believe the stage datagrepper process is messed up right now.

**Comment by johnbieren** [comment]
[test]

**Comment by johnbieren** [comment]
nope still broken

**Comment by johnbieren** [comment]
[test[

**Comment by bgoncalv** [comment]
lgtm, once this is merged we will need to redeploy the Jenkins instance?

**Comment by johnbieren** [comment]
@bgoncalv Nope, I can just add them to the pod's scriptApproval.xml file and restart the master. I am just raising this so if you ever do have to redeploy, there is one less headache to deal with. [merge]

**Pull request merged**
